import type { BatchCosting, CostAllocationRule } from "./costing-types";

// Batch Costings with detailed breakdown
export const batchCostings: BatchCosting[] = [
  {
    id: "bc-1",
    code: "BC-2025-0001",
    productionBatchId: "batch-1",
    batchNumber: "LOT-2025-0008",
    medicineName: "Paracetamol 500mg",
    medicineCode: "MED-001",
    quantityProduced: 50000,
    unit: "viên",
    productionStartDate: "2025-01-15",
    productionEndDate: "2025-01-20",
    materialCosts: [
      {
        id: "mc-1",
        materialId: "mat-1",
        materialCode: "MAT-001",
        materialName: "Paracetamol",
        quantity: 25,
        unit: "kg",
        unitCost: 850000,
        totalCost: 21250000,
        batchNumber: "LOT-MAT-2025-001",
        category: "raw_material",
      },
      {
        id: "mc-2",
        materialId: "mat-2",
        materialCode: "MAT-002",
        materialName: "Tinh bột ngô",
        quantity: 10,
        unit: "kg",
        unitCost: 45000,
        totalCost: 450000,
        batchNumber: "LOT-MAT-2025-002",
        category: "raw_material",
      },
      {
        id: "mc-3",
        materialId: "mat-3",
        materialCode: "MAT-PKG-001",
        materialName: "Vỉ nhôm",
        quantity: 5000,
        unit: "vỉ",
        unitCost: 1200,
        totalCost: 6000000,
        batchNumber: "LOT-PKG-2025-001",
        category: "packaging",
      },
    ],
    laborCosts: [
      {
        id: "lc-1",
        employeeName: "Trần Văn Anh",
        position: "Công nhân vận hành",
        shiftDate: "2025-01-15",
        hours: 8,
        hourlyRate: 50000,
        totalCost: 400000,
        productionPlanId: "pp-1",
      },
      {
        id: "lc-2",
        employeeName: "Nguyễn Thị Bình",
        position: "Công nhân vận hành",
        shiftDate: "2025-01-16",
        hours: 8,
        hourlyRate: 50000,
        totalCost: 400000,
        productionPlanId: "pp-1",
      },
      {
        id: "lc-3",
        employeeName: "Lê Văn Cường",
        position: "Kỹ thuật viên",
        shiftDate: "2025-01-15",
        hours: 8,
        hourlyRate: 80000,
        totalCost: 640000,
        productionPlanId: "pp-1",
      },
    ],
    overheadCosts: [
      {
        id: "oc-1",
        category: "Khấu hao máy móc",
        totalAmount: 5000000,
        allocationBase: "machine_hours",
        allocationRate: 125000,
        allocatedAmount: 2500000,
      },
      {
        id: "oc-2",
        category: "Điện nước",
        totalAmount: 3000000,
        allocationBase: "direct_labor_hours",
        allocationRate: 50000,
        allocatedAmount: 1200000,
      },
      {
        id: "oc-3",
        category: "Nhân công gián tiếp",
        totalAmount: 4000000,
        allocationBase: "units_produced",
        allocationRate: 60,
        allocatedAmount: 3000000,
      },
    ],
    totalMaterialCost: 27700000,
    totalLaborCost: 1440000,
    totalOverheadCost: 6700000,
    totalCost: 35840000,
    costPerUnit: 716.8,
    status: "completed",
    calculatedBy: "Nguyễn Văn An",
    calculatedAt: "2025-01-21T10:00:00Z",
    approvedBy: "Trương Thị Mai",
    approvedAt: "2025-01-21T14:30:00Z",
  },
  {
    id: "bc-2",
    code: "BC-2025-0002",
    productionBatchId: "batch-2",
    batchNumber: "LOT-2025-0009",
    medicineName: "Amoxicillin 500mg",
    medicineCode: "MED-002",
    quantityProduced: 30000,
    unit: "viên",
    productionStartDate: "2025-01-16",
    productionEndDate: "2025-01-21",
    materialCosts: [
      {
        id: "mc-4",
        materialId: "mat-4",
        materialCode: "MAT-004",
        materialName: "Amoxicillin Trihydrate",
        quantity: 17.5,
        unit: "kg",
        unitCost: 1200000,
        totalCost: 21000000,
        batchNumber: "LOT-MAT-2025-003",
        category: "raw_material",
      },
      {
        id: "mc-5",
        materialId: "mat-5",
        materialCode: "MAT-PKG-002",
        materialName: "Chai nhựa HDPE 100ml",
        quantity: 3000,
        unit: "chai",
        unitCost: 3500,
        totalCost: 10500000,
        batchNumber: "LOT-PKG-2025-002",
        category: "packaging",
      },
    ],
    laborCosts: [
      {
        id: "lc-4",
        employeeName: "Phạm Văn Dũng",
        position: "Công nhân vận hành",
        shiftDate: "2025-01-16",
        hours: 8,
        hourlyRate: 50000,
        totalCost: 400000,
        productionPlanId: "pp-2",
      },
    ],
    overheadCosts: [
      {
        id: "oc-4",
        category: "Khấu hao máy móc",
        totalAmount: 5000000,
        allocationBase: "machine_hours",
        allocationRate: 125000,
        allocatedAmount: 2000000,
      },
    ],
    totalMaterialCost: 31500000,
    totalLaborCost: 400000,
    totalOverheadCost: 2000000,
    totalCost: 33900000,
    costPerUnit: 1130,
    status: "completed",
    calculatedBy: "Nguyễn Văn An",
    calculatedAt: "2025-01-22T09:00:00Z",
  },
  {
    id: "bc-3",
    code: "BC-2025-0003",
    productionBatchId: "batch-3",
    batchNumber: "LOT-2025-0010",
    medicineName: "Vitamin C 1000mg",
    medicineCode: "MED-003",
    quantityProduced: 20000,
    unit: "viên",
    productionStartDate: "2025-01-18",
    productionEndDate: "2025-01-23",
    materialCosts: [
      {
        id: "mc-6",
        materialId: "mat-6",
        materialCode: "MAT-006",
        materialName: "Acid ascorbic",
        quantity: 20,
        unit: "kg",
        unitCost: 450000,
        totalCost: 9000000,
        batchNumber: "LOT-MAT-2025-004",
        category: "raw_material",
      },
    ],
    laborCosts: [],
    overheadCosts: [],
    totalMaterialCost: 9000000,
    totalLaborCost: 0,
    totalOverheadCost: 0,
    totalCost: 9000000,
    costPerUnit: 450,
    status: "calculating",
    calculatedBy: "Nguyễn Văn An",
    calculatedAt: "2025-01-24T08:00:00Z",
    notes: "Đang thu thập dữ liệu chi phí nhân công và overhead",
  },
];

// Cost Allocation Rules
export const costAllocationRules: CostAllocationRule[] = [
  {
    id: "rule-1",
    overheadCategory: "Khấu hao máy móc",
    allocationBase: "machine_hours",
    rate: 125000,
    isActive: true,
  },
  {
    id: "rule-2",
    overheadCategory: "Điện nước",
    allocationBase: "direct_labor_hours",
    rate: 50000,
    isActive: true,
  },
  {
    id: "rule-3",
    overheadCategory: "Nhân công gián tiếp",
    allocationBase: "units_produced",
    rate: 60,
    isActive: true,
  },
  {
    id: "rule-4",
    overheadCategory: "Bảo trì thiết bị",
    allocationBase: "machine_hours",
    rate: 75000,
    isActive: true,
  },
  {
    id: "rule-5",
    overheadCategory: "Kiểm tra chất lượng",
    allocationBase: "units_produced",
    rate: 25,
    isActive: true,
  },
];
