import type { Equipment, MaintenanceSchedule, MaintenanceRecord } from "./maintenance-types";

// Equipment inventory
export const equipmentList: Equipment[] = [
  {
    id: "eq-1",
    code: "EQ-MIX-001",
    name: "Máy trộn nguyên liệu 500L",
    category: "Mixing",
    location: "Khu A - Dây chuyền 1",
    manufacturer: "GEA Process Engineering",
    model: "MX-500-Pro",
    serialNumber: "GEA2023-MX-00145",
    purchaseDate: "2023-01-15",
    warrantyExpiry: "2026-01-15",
    status: "operational",
    lastMaintenanceDate: "2025-01-10",
    nextMaintenanceDate: "2025-02-10",
    operatingHours: 2450,
    documents: [],
  },
  {
    id: "eq-2",
    code: "EQ-DRY-001",
    name: "Máy sấy khô tầng sôi 300kg",
    category: "Drying",
    location: "Khu A - Dây chuyền 1",
    manufacturer: "Romaco Innojet",
    model: "FBD-300",
    serialNumber: "RMC2022-FBD-00892",
    purchaseDate: "2022-06-20",
    warrantyExpiry: "2025-06-20",
    status: "operational",
    lastMaintenanceDate: "2025-01-05",
    nextMaintenanceDate: "2025-04-05",
    operatingHours: 3820,
    documents: [],
  },
  {
    id: "eq-3",
    code: "EQ-PKG-001",
    name: "Máy đóng vỉ tự động 120 v/phút",
    category: "Packaging",
    location: "Khu B - Dây chuyền đóng gói",
    manufacturer: "Uhlmann Pac-Systeme",
    model: "UPS-120",
    serialNumber: "UHL2021-PKG-01234",
    purchaseDate: "2021-03-10",
    status: "maintenance",
    lastMaintenanceDate: "2025-01-20",
    nextMaintenanceDate: "2025-01-27",
    operatingHours: 5240,
    documents: [],
  },
  {
    id: "eq-4",
    code: "EQ-MIX-002",
    name: "Máy trộn nguyên liệu 1000L",
    category: "Mixing",
    location: "Khu A - Dây chuyền 2",
    manufacturer: "GEA Process Engineering",
    model: "MX-1000-Pro",
    serialNumber: "GEA2023-MX-00278",
    purchaseDate: "2023-05-20",
    warrantyExpiry: "2026-05-20",
    status: "operational",
    lastMaintenanceDate: "2024-12-15",
    nextMaintenanceDate: "2025-01-15",
    operatingHours: 1890,
    documents: [],
  },
  {
    id: "eq-5",
    code: "EQ-COMP-001",
    name: "Máy nén viên 200,000 viên/giờ",
    category: "Compression",
    location: "Khu A - Dây chuyền 1",
    manufacturer: "Fette Compacting",
    model: "FC-200K",
    serialNumber: "FET2020-COMP-05671",
    purchaseDate: "2020-09-15",
    status: "breakdown",
    lastMaintenanceDate: "2025-01-18",
    operatingHours: 6450,
    documents: [],
  },
  {
    id: "eq-6",
    code: "EQ-COAT-001",
    name: "Máy phủ màng viên nén 100kg",
    category: "Coating",
    location: "Khu A - Dây chuyền 1",
    manufacturer: "Accela Cota",
    model: "AC-100",
    serialNumber: "ACC2022-COAT-00345",
    purchaseDate: "2022-11-05",
    warrantyExpiry: "2025-11-05",
    status: "operational",
    lastMaintenanceDate: "2025-01-12",
    nextMaintenanceDate: "2025-02-12",
    operatingHours: 2180,
    documents: [],
  },
  {
    id: "eq-7",
    code: "EQ-PKG-002",
    name: "Máy đóng chai tự động 60 chai/phút",
    category: "Packaging",
    location: "Khu B - Dây chuyền đóng gói",
    manufacturer: "Bausch+Ströbel",
    model: "BST-60",
    serialNumber: "BST2021-PKG-09876",
    purchaseDate: "2021-07-22",
    status: "operational",
    lastMaintenanceDate: "2025-01-08",
    nextMaintenanceDate: "2025-03-08",
    operatingHours: 4120,
    documents: [],
  },
  {
    id: "eq-8",
    code: "EQ-LABEL-001",
    name: "Máy dán nhãn tự động",
    category: "Packaging",
    location: "Khu B - Dây chuyền đóng gói",
    manufacturer: "Krones Labellers",
    model: "KL-Auto-200",
    serialNumber: "KRN2023-LBL-00456",
    purchaseDate: "2023-02-14",
    warrantyExpiry: "2026-02-14",
    status: "operational",
    lastMaintenanceDate: "2024-12-20",
    nextMaintenanceDate: "2025-01-20",
    operatingHours: 1650,
    documents: [],
  },
];

// Maintenance Schedules
export const maintenanceSchedules: MaintenanceSchedule[] = [
  {
    id: "ms-1",
    code: "MS-2025-0001",
    equipmentId: "eq-1",
    equipmentCode: "EQ-MIX-001",
    equipmentName: "Máy trộn nguyên liệu 500L",
    type: "preventive",
    frequency: "Hàng tháng",
    frequencyDays: 30,
    lastPerformed: "2025-01-10",
    nextDue: "2025-02-10",
    estimatedDuration: 4,
    assignedTo: "Nguyễn Văn Bảo",
    checklist: [
      { id: "task-1", description: "Kiểm tra và vệ sinh bộ phận trộn", isCompleted: false },
      { id: "task-2", description: "Kiểm tra hệ thống động cơ", isCompleted: false },
      { id: "task-3", description: "Bôi trơn các bộ phận chuyển động", isCompleted: false },
      { id: "task-4", description: "Kiểm tra hệ thống điện", isCompleted: false },
    ],
    isActive: true,
  },
  {
    id: "ms-2",
    code: "MS-2025-0002",
    equipmentId: "eq-2",
    equipmentCode: "EQ-DRY-001",
    equipmentName: "Máy sấy khô tầng sôi 300kg",
    type: "preventive",
    frequency: "Mỗi 3 tháng",
    frequencyDays: 90,
    lastPerformed: "2025-01-05",
    nextDue: "2025-04-05",
    estimatedDuration: 6,
    assignedTo: "Trần Văn Cường",
    checklist: [
      { id: "task-5", description: "Kiểm tra và thay thế bộ lọc không khí", isCompleted: false },
      { id: "task-6", description: "Kiểm tra hệ thống nhiệt", isCompleted: false },
      { id: "task-7", description: "Hiệu chuẩn cảm biến nhiệt độ", isCompleted: false },
      { id: "task-8", description: "Vệ sinh buồng sấy", isCompleted: false },
    ],
    isActive: true,
  },
  {
    id: "ms-3",
    code: "MS-2025-0003",
    equipmentId: "eq-6",
    equipmentCode: "EQ-COAT-001",
    equipmentName: "Máy phủ màng viên nén 100kg",
    type: "calibration",
    frequency: "Mỗi 6 tháng",
    frequencyDays: 180,
    lastPerformed: "2024-08-12",
    nextDue: "2025-02-12",
    estimatedDuration: 8,
    assignedTo: "Lê Thị Dung",
    checklist: [
      { id: "task-9", description: "Hiệu chuẩn cảm biến nhiệt độ", isCompleted: false },
      { id: "task-10", description: "Hiệu chuẩn cảm biến độ ẩm", isCompleted: false },
      { id: "task-11", description: "Kiểm tra tốc độ quay trống", isCompleted: false },
    ],
    isActive: true,
  },
  {
    id: "ms-4",
    code: "MS-2025-0004",
    equipmentId: "eq-4",
    equipmentCode: "EQ-MIX-002",
    equipmentName: "Máy trộn nguyên liệu 1000L",
    type: "preventive",
    frequency: "Hàng tháng",
    frequencyDays: 30,
    lastPerformed: "2024-12-15",
    nextDue: "2025-01-15",
    estimatedDuration: 4,
    checklist: [
      { id: "task-12", description: "Kiểm tra và vệ sinh bộ phận trộn", isCompleted: false },
      { id: "task-13", description: "Bôi trơn các bộ phận chuyển động", isCompleted: false },
    ],
    isActive: true,
  },
];

// Maintenance Records
export const maintenanceRecords: MaintenanceRecord[] = [
  {
    id: "mr-1",
    code: "MR-2025-0001",
    equipmentId: "eq-1",
    equipmentCode: "EQ-MIX-001",
    equipmentName: "Máy trộn nguyên liệu 500L",
    scheduleId: "ms-1",
    type: "preventive",
    priority: "medium",
    description: "Bảo dưỡng định kỳ tháng 1/2025",
    reportedBy: "Hệ thống",
    reportedAt: "2025-01-05T08:00:00Z",
    assignedTo: "Nguyễn Văn Bảo",
    scheduledDate: "2025-01-10",
    startedAt: "2025-01-10T07:30:00Z",
    completedAt: "2025-01-10T11:45:00Z",
    status: "completed",
    tasks: [
      {
        id: "task-1",
        description: "Kiểm tra và vệ sinh bộ phận trộn",
        isCompleted: true,
        completedBy: "Nguyễn Văn Bảo",
        completedAt: "2025-01-10T08:30:00Z",
      },
      {
        id: "task-2",
        description: "Kiểm tra hệ thống động cơ",
        isCompleted: true,
        completedBy: "Nguyễn Văn Bảo",
        completedAt: "2025-01-10T09:45:00Z",
      },
      {
        id: "task-3",
        description: "Bôi trơn các bộ phận chuyển động",
        isCompleted: true,
        completedBy: "Nguyễn Văn Bảo",
        completedAt: "2025-01-10T10:30:00Z",
      },
    ],
    spareParts: [
      {
        id: "sp-1",
        materialId: "mat-sp-001",
        materialName: "Dầu bôi trơn công nghiệp 5L",
        quantity: 2,
        unitCost: 450000,
      },
    ],
    laborHours: 4.25,
    cost: 950000,
    notes: "Bảo dưỡng hoàn tất, thiết bị hoạt động bình thường",
    documents: [],
  },
  {
    id: "mr-2",
    code: "MR-2025-0002",
    equipmentId: "eq-5",
    equipmentCode: "EQ-COMP-001",
    equipmentName: "Máy nén viên 200,000 viên/giờ",
    type: "corrective",
    priority: "critical",
    description: "Sửa chữa hư hỏng bộ phận nén",
    reportedBy: "Phạm Văn Hải",
    reportedAt: "2025-01-18T14:30:00Z",
    assignedTo: "Trần Văn Cường",
    scheduledDate: "2025-01-18",
    startedAt: "2025-01-18T15:00:00Z",
    status: "in_progress",
    tasks: [
      {
        id: "task-14",
        description: "Kiểm tra và chẩn đoán lỗi",
        isCompleted: true,
        completedBy: "Trần Văn Cường",
        completedAt: "2025-01-18T15:30:00Z",
      },
      {
        id: "task-15",
        description: "Thay thế bộ phận nén",
        isCompleted: false,
      },
      {
        id: "task-16",
        description: "Kiểm tra và chạy thử",
        isCompleted: false,
      },
    ],
    spareParts: [
      {
        id: "sp-2",
        materialId: "mat-sp-002",
        materialName: "Bộ phận nén thay thế",
        quantity: 1,
        unitCost: 15000000,
      },
    ],
    laborHours: 0,
    cost: 0,
    notes: "Đang chờ phụ tùng từ nhà cung cấp",
    documents: [],
  },
  {
    id: "mr-3",
    code: "MR-2025-0003",
    equipmentId: "eq-3",
    equipmentCode: "EQ-PKG-001",
    equipmentName: "Máy đóng vỉ tự động 120 v/phút",
    type: "preventive",
    priority: "medium",
    description: "Bảo dưỡng định kỳ",
    reportedBy: "Hệ thống",
    reportedAt: "2025-01-15T08:00:00Z",
    assignedTo: "Lê Thị Dung",
    scheduledDate: "2025-01-20",
    startedAt: "2025-01-20T08:00:00Z",
    completedAt: "2025-01-20T16:30:00Z",
    status: "completed",
    tasks: [
      {
        id: "task-17",
        description: "Vệ sinh toàn bộ máy",
        isCompleted: true,
        completedBy: "Lê Thị Dung",
        completedAt: "2025-01-20T10:00:00Z",
      },
      {
        id: "task-18",
        description: "Kiểm tra hệ thống nhiệt hàn",
        isCompleted: true,
        completedBy: "Lê Thị Dung",
        completedAt: "2025-01-20T12:00:00Z",
      },
      {
        id: "task-19",
        description: "Hiệu chuẩn cảm biến",
        isCompleted: true,
        completedBy: "Lê Thị Dung",
        completedAt: "2025-01-20T14:30:00Z",
      },
    ],
    spareParts: [],
    laborHours: 8.5,
    cost: 1200000,
    documents: [],
  },
  {
    id: "mr-4",
    code: "MR-2025-0004",
    equipmentId: "eq-2",
    equipmentCode: "EQ-DRY-001",
    equipmentName: "Máy sấy khô tầng sôi 300kg",
    scheduleId: "ms-2",
    type: "preventive",
    priority: "medium",
    description: "Bảo dưỡng định kỳ quý 1/2025",
    reportedBy: "Hệ thống",
    reportedAt: "2024-12-30T08:00:00Z",
    assignedTo: "Trần Văn Cường",
    scheduledDate: "2025-01-05",
    startedAt: "2025-01-05T07:00:00Z",
    completedAt: "2025-01-05T15:30:00Z",
    status: "completed",
    tasks: [
      {
        id: "task-20",
        description: "Kiểm tra và thay thế bộ lọc không khí",
        isCompleted: true,
        completedBy: "Trần Văn Cường",
        completedAt: "2025-01-05T09:00:00Z",
      },
      {
        id: "task-21",
        description: "Vệ sinh buồng sấy",
        isCompleted: true,
        completedBy: "Trần Văn Cường",
        completedAt: "2025-01-05T12:00:00Z",
      },
    ],
    spareParts: [
      {
        id: "sp-3",
        materialId: "mat-sp-003",
        materialName: "Bộ lọc không khí HEPA",
        quantity: 2,
        unitCost: 3500000,
      },
    ],
    laborHours: 8.5,
    cost: 8200000,
    documents: [],
  },
  {
    id: "mr-5",
    code: "MR-2025-0005",
    equipmentId: "eq-7",
    equipmentCode: "EQ-PKG-002",
    equipmentName: "Máy đóng chai tự động 60 chai/phút",
    type: "corrective",
    priority: "high",
    description: "Sửa chữa hệ thống đóng nắp",
    reportedBy: "Võ Thị Mai",
    reportedAt: "2025-01-15T10:00:00Z",
    assignedTo: "Nguyễn Văn Bảo",
    scheduledDate: "2025-01-16",
    startedAt: "2025-01-16T08:00:00Z",
    completedAt: "2025-01-16T12:30:00Z",
    status: "completed",
    tasks: [
      {
        id: "task-22",
        description: "Chẩn đoán lỗi hệ thống đóng nắp",
        isCompleted: true,
        completedBy: "Nguyễn Văn Bảo",
        completedAt: "2025-01-16T09:00:00Z",
      },
      {
        id: "task-23",
        description: "Thay thế bộ phận đóng nắp",
        isCompleted: true,
        completedBy: "Nguyễn Văn Bảo",
        completedAt: "2025-01-16T11:00:00Z",
      },
    ],
    spareParts: [
      {
        id: "sp-4",
        materialId: "mat-sp-004",
        materialName: "Bộ đóng nắp thay thế",
        quantity: 1,
        unitCost: 5200000,
      },
    ],
    laborHours: 4.5,
    cost: 5800000,
    documents: [],
  },
];
