import type {
  User,
  PurchaseRequisition,
  Supplier,
  PurchaseOrder,
  QualityInspection,
  InventoryItem,
  Material,
  RFQ,
  Quotation,
  Medicine,
  SalesOrder,
  ProductionPlan,
  ProductionLine,
  ProductionLineSchedule,
  ResourceAllocation,
  ProductionCapacity,
  BOMFormula,
  BOMItem,
  FormulaVersion,
  MaterialRequirement,
} from "./types"
import type {
  ProductionBatch,
  StockTransaction,
  BatchInventory,
} from "./warehouse-types"

export const currentUser: User = {
  id: "user-1",
  name: "Nguyễn Văn An",
  email: "an.nguyen@pharma.vn",
  role: "requester",
  department: "Sản xuất",
  avatar: "/placeholder.svg?height=40&width=40",
}

export const users: User[] = [
  currentUser,
  {
    id: "user-2",
    name: "Trần Thị Bình",
    email: "binh.tran@pharma.vn",
    role: "department_head",
    department: "Sản xuất",
  },
  {
    id: "user-3",
    name: "Lê Văn Cường",
    email: "cuong.le@pharma.vn",
    role: "procurement",
    department: "Mua hàng",
  },
  {
    id: "user-4",
    name: "Phạm Thị Dung",
    email: "dung.pham@pharma.vn",
    role: "procurement_manager",
    department: "Mua hàng",
  },
  {
    id: "user-5",
    name: "Hoàng Văn Em",
    email: "em.hoang@pharma.vn",
    role: "qa_qc",
    department: "QA/QC",
  },
  {
    id: "user-6",
    name: "Vũ Thị Phương",
    email: "phuong.vu@pharma.vn",
    role: "warehouse",
    department: "Kho",
  },
  {
    id: "user-7",
    name: "Đặng Văn Giang",
    email: "giang.dang@pharma.vn",
    role: "accounting",
    department: "Kế toán",
  },
  {
    id: "user-8",
    name: "Ngô Thị Hương",
    email: "huong.ngo@pharma.vn",
    role: "director",
    department: "Ban Giám đốc",
  },
  {
    id: "user-9",
    name: "Bùi Văn Inh",
    email: "inh.bui@pharma.vn",
    role: "admin",
    department: "IT",
  },
  {
    id: "user-10",
    name: "Võ Thị Kim",
    email: "kim.vo@pharma.vn",
    role: "production_planner",
    department: "Hoạch định Sản xuất",
  },
]

export const materials: Material[] = [
  {
    id: "mat-1",
    code: "NL-001",
    name: "Paracetamol",
    category: "Nguyên liệu",
    unit: "kg",
    minStock: 100,
    currentStock: 250,
  },
  {
    id: "mat-2",
    code: "NL-002",
    name: "Amoxicillin Trihydrate",
    category: "Nguyên liệu",
    unit: "kg",
    minStock: 50,
    currentStock: 30,
  },
  {
    id: "mat-3",
    code: "TĐ-001",
    name: "Tinh bột ngô",
    category: "Tá dược",
    unit: "kg",
    minStock: 200,
    currentStock: 180,
  },
  {
    id: "mat-4",
    code: "TĐ-002",
    name: "Lactose monohydrate",
    category: "Tá dược",
    unit: "kg",
    minStock: 150,
    currentStock: 420,
  },
  {
    id: "mat-5",
    code: "BB-001",
    name: "Chai nhựa HDPE 100ml",
    category: "Bao bì",
    unit: "cái",
    minStock: 10000,
    currentStock: 8500,
  },
  {
    id: "mat-6",
    code: "BB-002",
    name: "Vỉ nhôm PVC/Alu",
    category: "Bao bì",
    unit: "cuộn",
    minStock: 100,
    currentStock: 75,
  },
]

export const purchaseRequisitions: PurchaseRequisition[] = [
  {
    id: "pr-1",
    code: "PR-2026-0001",
    requesterId: "user-1",
    requesterName: "Nguyễn Văn An",
    department: "Sản xuất",
    items: [
      {
        id: "item-1",
        materialId: "mat-2",
        materialName: "Amoxicillin Trihydrate",
        materialCode: "NL-002",
        unit: "kg",
        quantity: 100,
        currentStock: 30,
        note: "Cần gấp cho lô sản xuất tháng 2",
      },
      {
        id: "item-2",
        materialId: "mat-3",
        materialName: "Tinh bột ngô",
        materialCode: "TĐ-001",
        unit: "kg",
        quantity: 200,
        currentStock: 180,
      },
    ],
    purpose: "Sản xuất lô thuốc kháng sinh Amoxicillin 500mg",
    requiredDate: "2026-02-15",
    status: "pending",
    createdAt: "2026-01-10T08:30:00Z",
    updatedAt: "2026-01-10T08:30:00Z",
    approvalHistory: [],
  },
  {
    id: "pr-2",
    code: "PR-2026-0002",
    requesterId: "user-1",
    requesterName: "Nguyễn Văn An",
    department: "Sản xuất",
    items: [
      {
        id: "item-3",
        materialId: "mat-6",
        materialName: "Vỉ nhôm PVC/Alu",
        materialCode: "BB-002",
        unit: "cuộn",
        quantity: 50,
        currentStock: 75,
      },
    ],
    purpose: "Đóng gói sản phẩm viên nén",
    requiredDate: "2026-02-01",
    status: "approved",
    createdAt: "2026-01-08T10:00:00Z",
    updatedAt: "2026-01-09T14:30:00Z",
    approvalHistory: [
      {
        id: "step-1",
        approverId: "user-2",
        approverName: "Trần Thị Bình",
        role: "Trưởng bộ phận",
        status: "approved",
        comment: "Đồng ý. Đề nghị ưu tiên xử lý.",
        timestamp: "2026-01-09T14:30:00Z",
      },
    ],
  },
  {
    id: "pr-3",
    code: "PR-2026-0003",
    requesterId: "user-1",
    requesterName: "Nguyễn Văn An",
    department: "Sản xuất",
    items: [
      {
        id: "item-4",
        materialId: "mat-1",
        materialName: "Paracetamol",
        materialCode: "NL-001",
        unit: "kg",
        quantity: 50,
        currentStock: 250,
      },
    ],
    purpose: "Sản xuất thuốc giảm đau",
    requiredDate: "2026-01-25",
    status: "rejected",
    createdAt: "2026-01-05T09:00:00Z",
    updatedAt: "2026-01-06T11:00:00Z",
    approvalHistory: [
      {
        id: "step-2",
        approverId: "user-2",
        approverName: "Trần Thị Bình",
        role: "Trưởng bộ phận",
        status: "rejected",
        comment: "Tồn kho hiện tại đủ dùng. Đề nghị hoãn lại.",
        timestamp: "2026-01-06T11:00:00Z",
      },
    ],
  },
]

export const suppliers: Supplier[] = [
  {
    id: "sup-1",
    code: "NCC-001",
    name: "Công ty TNHH Nguyên liệu Dược phẩm Á Châu",
    address: "123 Đường Nguyễn Văn Linh, Q.7, TP.HCM",
    phone: "028-3771-0001",
    email: "contact@asia-pharma.vn",
    taxCode: "0312345678",
    gmpCertificate: "GMP-2024-001",
    gmpExpiry: "2027-06-30",
    coCertificate: "CO-2024-001",
    cqCertificate: "CQ-2024-001",
    rating: 4.5,
    status: "active",
    transactionHistory: [
      { id: "tx-1", poCode: "PO-2025-0150", date: "2025-12-15", amount: 450000000, status: "completed" },
      { id: "tx-2", poCode: "PO-2025-0142", date: "2025-11-20", amount: 280000000, status: "completed" },
    ],
  },
  {
    id: "sup-2",
    code: "NCC-002",
    name: "Công ty CP Hóa Dược Việt Nam",
    address: "456 Đường Lê Lợi, Q.1, TP.HCM",
    phone: "028-3822-0002",
    email: "sales@hoaduocvn.com",
    taxCode: "0301234567",
    gmpCertificate: "GMP-2023-045",
    gmpExpiry: "2026-12-31",
    rating: 4.2,
    status: "active",
    transactionHistory: [
      { id: "tx-3", poCode: "PO-2025-0148", date: "2025-12-10", amount: 320000000, status: "completed" },
    ],
  },
  {
    id: "sup-3",
    code: "NCC-003",
    name: "Công ty TNHH Bao bì Y tế Sài Gòn",
    address: "789 Đường Cách Mạng Tháng 8, Q.3, TP.HCM",
    phone: "028-3930-0003",
    email: "info@baobiyte.vn",
    taxCode: "0309876543",
    rating: 3.8,
    status: "active",
    transactionHistory: [],
  },
]

export const rfqs: RFQ[] = [
  {
    id: "rfq-1",
    code: "RFQ-2026-0001",
    requisitionId: "pr-2",
    suppliers: ["sup-1", "sup-2"],
    items: [{ materialId: "mat-6", materialName: "Vỉ nhôm PVC/Alu", quantity: 50, unit: "cuộn" }],
    deadline: "2026-01-20",
    status: "received",
    createdAt: "2026-01-10T09:00:00Z",
  },
]

export const quotations: Quotation[] = [
  {
    id: "quot-1",
    rfqId: "rfq-1",
    supplierId: "sup-1",
    supplierName: "Công ty TNHH Nguyên liệu Dược phẩm Á Châu",
    items: [{ materialId: "mat-6", unitPrice: 2500000, quantity: 50, totalPrice: 125000000 }],
    deliveryTime: 7,
    paymentTerms: "30 ngày sau giao hàng",
    validUntil: "2026-02-10",
    totalAmount: 125000000,
    submittedAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "quot-2",
    rfqId: "rfq-1",
    supplierId: "sup-2",
    supplierName: "Công ty CP Hóa Dược Việt Nam",
    items: [{ materialId: "mat-6", unitPrice: 2400000, quantity: 50, totalPrice: 120000000 }],
    deliveryTime: 10,
    paymentTerms: "50% trước, 50% sau giao hàng",
    validUntil: "2026-02-05",
    totalAmount: 120000000,
    submittedAt: "2026-01-14T14:00:00Z",
  },
]

export const purchaseOrders: PurchaseOrder[] = [
  {
    id: "po-1",
    code: "PO-2026-0001",
    supplierId: "sup-2",
    supplierName: "Công ty CP Hóa Dược Việt Nam",
    requisitionId: "pr-2",
    quotationId: "quot-2",
    items: [
      {
        materialId: "mat-6",
        materialName: "Vỉ nhôm PVC/Alu",
        quantity: 50,
        unit: "cuộn",
        unitPrice: 2400000,
        totalPrice: 120000000,
      },
    ],
    totalAmount: 120000000,
    status: "processing",
    deliveryDate: "2026-01-25",
    paymentTerms: "50% trước, 50% sau giao hàng",
    createdAt: "2026-01-16T09:00:00Z",
    approvedAt: "2026-01-16T14:00:00Z",
  },
]

export const qualityInspections: QualityInspection[] = [
  {
    id: "qi-1",
    code: "QI-2026-0001",
    poId: "po-1",
    poCode: "PO-2026-0001",
    supplierId: "sup-2",
    supplierName: "Công ty CP Hóa Dược Việt Nam",
    batchNumber: "LOT-2026-001",
    items: [
      {
        materialId: "mat-6",
        materialName: "Vỉ nhôm PVC/Alu",
        quantity: 50,
      },
    ],
    status: "waiting",
    documents: [],
  },
]

export const inventoryItems: InventoryItem[] = [
  {
    id: "inv-1",
    materialId: "mat-1",
    materialCode: "NL-001",
    materialName: "Paracetamol",
    batchNumber: "LOT-2025-150",
    quantity: 150,
    unit: "kg",
    location: "Kho A1-01",
    expiryDate: "2027-06-30",
    receivedDate: "2025-12-01",
    supplierId: "sup-1",
    supplierName: "Công ty TNHH Nguyên liệu Dược phẩm Á Châu",
    poId: "PO-2025-0150",
  },
  {
    id: "inv-2",
    materialId: "mat-1",
    materialCode: "NL-001",
    materialName: "Paracetamol",
    batchNumber: "LOT-2025-148",
    quantity: 100,
    unit: "kg",
    location: "Kho A1-02",
    expiryDate: "2027-03-15",
    receivedDate: "2025-11-15",
    supplierId: "sup-1",
    supplierName: "Công ty TNHH Nguyên liệu Dược phẩm Á Châu",
    poId: "PO-2025-0148",
  },
  {
    id: "inv-3",
    materialId: "mat-2",
    materialCode: "NL-002",
    materialName: "Amoxicillin Trihydrate",
    batchNumber: "LOT-2025-142",
    quantity: 30,
    unit: "kg",
    location: "Kho A2-01",
    expiryDate: "2026-09-30",
    receivedDate: "2025-10-20",
    supplierId: "sup-2",
    supplierName: "Công ty CP Hóa Dược Việt Nam",
    poId: "PO-2025-0142",
  },
  {
    id: "inv-4",
    materialId: "mat-4",
    materialCode: "TĐ-002",
    materialName: "Lactose monohydrate",
    batchNumber: "LOT-2025-155",
    quantity: 420,
    unit: "kg",
    location: "Kho B1-01",
    expiryDate: "2028-01-31",
    receivedDate: "2025-12-10",
    supplierId: "sup-1",
    supplierName: "Công ty TNHH Nguyên liệu Dược phẩm Á Châu",
    poId: "PO-2025-0155",
  },
]

export const roleLabels: Record<string, string> = {
  requester: "Nhân viên đề xuất",
  department_head: "Trưởng bộ phận",
  procurement: "Phòng Mua hàng",
  procurement_manager: "Quản lý Mua hàng",
  qa_qc: "QA/QC",
  warehouse: "Thủ kho",
  accounting: "Kế toán",
  director: "Ban Giám đốc",
  admin: "Quản trị hệ thống",
  production_planner: "Hoạch định Sản xuất",
}

export const statusLabels: Record<string, string> = {
  pending: "Chờ duyệt",
  approved: "Đã duyệt",
  rejected: "Từ chối",
  processing: "Đang xử lý",
  completed: "Hoàn thành",
  waiting: "Chờ kiểm nghiệm",
  passed: "Đạt",
  failed: "Không đạt",
  draft: "Bản nháp",
  sent: "Đã gửi",
  received: "Đã nhận báo giá",
  closed: "Đã đóng",
  active: "Hoạt động",
  inactive: "Ngừng hoạt động",
  in_progress: "Đang sản xuất",
  on_hold: "Tạm dừng",
  cancelled: "Đã hủy",
  planned: "Đã lập kế hoạch",
  in_production: "Đang sản xuất",
  low: "Thấp",
  medium: "Trung bình",
  high: "Cao",
  urgent: "Khẩn cấp",
  operational: "Hoạt động tốt",
  maintenance: "Bảo trì",
  faulty: "Hỏng hóc",
}

// Production Planning Mock Data

export const medicines: Medicine[] = [
  {
    id: "med-1",
    code: "MED-VN-001",
    name: "Paracetamol 500mg",
    type: "tablet",
    dosage: "500mg",
    unit: "viên",
    description: "Thuốc giảm đau, hạ sốt",
    registrationNumber: "VD-12345-15",
    materials: [
      { materialId: "mat-1", materialName: "Paracetamol", quantityPerUnit: 0.5, unit: "g" },
      { materialId: "mat-3", materialName: "Tinh bột ngô", quantityPerUnit: 0.2, unit: "g" },
    ],
  },
  {
    id: "med-2",
    code: "MED-VN-002",
    name: "Amoxicillin 500mg",
    type: "capsule",
    dosage: "500mg",
    unit: "viên",
    description: "Kháng sinh nhóm Beta-lactam",
    registrationNumber: "VD-12346-15",
    materials: [
      { materialId: "mat-2", materialName: "Amoxicillin Trihydrate", quantityPerUnit: 0.6, unit: "g" },
      { materialId: "mat-4", materialName: "Lactose monohydrate", quantityPerUnit: 0.15, unit: "g" },
    ],
  },
  {
    id: "med-3",
    code: "MED-VN-003",
    name: "Siro ho trẻ em 100ml",
    type: "syrup",
    dosage: "100ml",
    unit: "chai",
    description: "Siro trị ho cho trẻ em",
    registrationNumber: "VD-12347-15",
    materials: [
      { materialId: "mat-1", materialName: "Paracetamol", quantityPerUnit: 1.2, unit: "g" },
    ],
  },
  {
    id: "med-4",
    code: "MED-VN-004",
    name: "Vitamin C 1000mg",
    type: "tablet",
    dosage: "1000mg",
    unit: "viên",
    description: "Bổ sung vitamin C",
    registrationNumber: "VD-12348-15",
    materials: [
      { materialId: "mat-3", materialName: "Tinh bột ngô", quantityPerUnit: 0.3, unit: "g" },
    ],
  },
]

export const productionLines: ProductionLine[] = [
  {
    id: "line-1",
    code: "LINE-TAB-01",
    name: "Dây chuyền viên nén số 1",
    type: "tablet",
    capacityPerShift: 50000,
    capacityUnit: "viên",
    status: "active",
    description: "Dây chuyền sản xuất viên nén tự động",
  },
  {
    id: "line-2",
    code: "LINE-TAB-02",
    name: "Dây chuyền viên nén số 2",
    type: "tablet",
    capacityPerShift: 45000,
    capacityUnit: "viên",
    status: "active",
  },
  {
    id: "line-3",
    code: "LINE-CAP-01",
    name: "Dây chuyền viên nang số 1",
    type: "capsule",
    capacityPerShift: 40000,
    capacityUnit: "viên",
    status: "active",
    description: "Dây chuyền sản xuất viên nang gelatin cứng",
  },
  {
    id: "line-4",
    code: "LINE-SYR-01",
    name: "Dây chuyền xi-rô số 1",
    type: "syrup",
    capacityPerShift: 2000,
    capacityUnit: "chai",
    status: "active",
  },
  {
    id: "line-5",
    code: "LINE-TAB-03",
    name: "Dây chuyền viên nén số 3",
    type: "tablet",
    capacityPerShift: 40000,
    capacityUnit: "viên",
    status: "maintenance",
    description: "Đang bảo trì định kỳ",
  },
]

export const salesOrders: SalesOrder[] = [
  {
    id: "so-1",
    code: "SO-2026-0001",
    customerName: "Công ty CP Dược phẩm Bắc Ninh",
    items: [
      {
        id: "so-item-1",
        medicineId: "med-1",
        medicineName: "Paracetamol 500mg",
        medicineCode: "MED-VN-001",
        quantity: 100000,
        unit: "viên",
      },
      {
        id: "so-item-2",
        medicineId: "med-4",
        medicineName: "Vitamin C 1000mg",
        medicineCode: "MED-VN-004",
        quantity: 50000,
        unit: "viên",
      },
    ],
    orderDate: "2026-01-20",
    requiredDate: "2026-02-10",
    status: "pending",
    priority: "high",
    createdAt: "2026-01-20T09:00:00Z",
    notes: "Đơn hàng ưu tiên, cần giao trước Tết",
  },
  {
    id: "so-2",
    code: "SO-2026-0002",
    customerName: "Công ty TNHH Dược phẩm Hà Nội",
    items: [
      {
        id: "so-item-3",
        medicineId: "med-2",
        medicineName: "Amoxicillin 500mg",
        medicineCode: "MED-VN-002",
        quantity: 80000,
        unit: "viên",
      },
    ],
    orderDate: "2026-01-22",
    requiredDate: "2026-02-15",
    status: "planned",
    priority: "medium",
    createdAt: "2026-01-22T10:30:00Z",
  },
  {
    id: "so-3",
    code: "SO-2026-0003",
    customerName: "Bệnh viện Đa khoa Tỉnh",
    items: [
      {
        id: "so-item-4",
        medicineId: "med-3",
        medicineName: "Siro ho trẻ em 100ml",
        medicineCode: "MED-VN-003",
        quantity: 5000,
        unit: "chai",
      },
    ],
    orderDate: "2026-01-23",
    requiredDate: "2026-02-20",
    status: "pending",
    priority: "urgent",
    createdAt: "2026-01-23T14:00:00Z",
    notes: "Đơn hàng khẩn cấp cho chương trình miễn phí",
  },
]

export const productionPlans: ProductionPlan[] = [
  {
    id: "pp-1",
    code: "PP-2026-0001",
    salesOrderId: "so-2",
    salesOrderCode: "SO-2026-0002",
    plannerId: "user-10",
    plannerName: "Võ Thị Kim",
    items: [
      {
        id: "pp-item-1",
        medicineId: "med-2",
        medicineName: "Amoxicillin 500mg",
        medicineCode: "MED-VN-002",
        medicineType: "capsule",
        plannedQuantity: 80000,
        unit: "viên",
        productionLineId: "line-3",
        estimatedDuration: 2,
      },
    ],
    startDate: "2026-01-27",
    endDate: "2026-01-29",
    status: "approved",
    createdAt: "2026-01-23T09:00:00Z",
    updatedAt: "2026-01-23T14:00:00Z",
    approvedBy: "user-8",
    approvedAt: "2026-01-23T14:00:00Z",
  },
  {
    id: "pp-2",
    code: "PP-2026-0002",
    salesOrderId: "so-1",
    salesOrderCode: "SO-2026-0001",
    plannerId: "user-10",
    plannerName: "Võ Thị Kim",
    items: [
      {
        id: "pp-item-2",
        medicineId: "med-1",
        medicineName: "Paracetamol 500mg",
        medicineCode: "MED-VN-001",
        medicineType: "tablet",
        plannedQuantity: 100000,
        unit: "viên",
        productionLineId: "line-1",
        estimatedDuration: 3,
      },
      {
        id: "pp-item-3",
        medicineId: "med-4",
        medicineName: "Vitamin C 1000mg",
        medicineCode: "MED-VN-004",
        medicineType: "tablet",
        plannedQuantity: 50000,
        unit: "viên",
        productionLineId: "line-2",
        estimatedDuration: 2,
      },
    ],
    startDate: "2026-01-28",
    endDate: "2026-02-05",
    status: "draft",
    createdAt: "2026-01-24T10:00:00Z",
    updatedAt: "2026-01-24T10:00:00Z",
    notes: "Chờ duyệt từ Ban Giám đốc",
  },
]

export const productionLineSchedules: ProductionLineSchedule[] = [
  {
    id: "sched-1",
    productionLineId: "line-3",
    productionLineName: "Dây chuyền viên nang số 1",
    productionPlanId: "pp-1",
    productionPlanCode: "PP-2026-0001",
    medicineId: "med-2",
    medicineName: "Amoxicillin 500mg",
    quantity: 40000,
    date: "2026-01-27",
    shift: "morning",
    status: "in_progress",
    assignedWorkers: 12,
  },
  {
    id: "sched-2",
    productionLineId: "line-3",
    productionLineName: "Dây chuyền viên nang số 1",
    productionPlanId: "pp-1",
    productionPlanCode: "PP-2026-0001",
    medicineId: "med-2",
    medicineName: "Amoxicillin 500mg",
    quantity: 40000,
    date: "2026-01-27",
    shift: "afternoon",
    status: "approved",
    assignedWorkers: 12,
  },
  {
    id: "sched-3",
    productionLineId: "line-1",
    productionLineName: "Dây chuyền viên nén số 1",
    productionPlanId: "pp-2",
    productionPlanCode: "PP-2026-0002",
    medicineId: "med-1",
    medicineName: "Paracetamol 500mg",
    quantity: 50000,
    date: "2026-01-28",
    shift: "morning",
    status: "approved",
    assignedWorkers: 10,
  },
  {
    id: "sched-4",
    productionLineId: "line-1",
    productionLineName: "Dây chuyền viên nén số 1",
    productionPlanId: "pp-2",
    productionPlanCode: "PP-2026-0002",
    medicineId: "med-1",
    medicineName: "Paracetamol 500mg",
    quantity: 50000,
    date: "2026-01-28",
    shift: "afternoon",
    status: "approved",
    assignedWorkers: 10,
  },
]

export const resourceAllocations: ResourceAllocation[] = [
  {
    id: "res-1",
    productionLineId: "line-1",
    productionLineName: "Dây chuyền viên nén số 1",
    date: "2026-01-28",
    shift: "morning",
    assignedWorkers: 10,
    requiredWorkers: 10,
    machineryStatus: "operational",
    utilizationRate: 100,
  },
  {
    id: "res-2",
    productionLineId: "line-1",
    productionLineName: "Dây chuyền viên nén số 1",
    date: "2026-01-28",
    shift: "afternoon",
    assignedWorkers: 10,
    requiredWorkers: 10,
    machineryStatus: "operational",
    utilizationRate: 100,
  },
  {
    id: "res-3",
    productionLineId: "line-3",
    productionLineName: "Dây chuyền viên nang số 1",
    date: "2026-01-27",
    shift: "morning",
    assignedWorkers: 12,
    requiredWorkers: 12,
    machineryStatus: "operational",
    utilizationRate: 100,
  },
  {
    id: "res-4",
    productionLineId: "line-3",
    productionLineName: "Dây chuyền viên nang số 1",
    date: "2026-01-27",
    shift: "afternoon",
    assignedWorkers: 12,
    requiredWorkers: 12,
    machineryStatus: "operational",
    utilizationRate: 100,
  },
  {
    id: "res-5",
    productionLineId: "line-2",
    productionLineName: "Dây chuyền viên nén số 2",
    date: "2026-01-28",
    shift: "morning",
    assignedWorkers: 8,
    requiredWorkers: 10,
    machineryStatus: "operational",
    utilizationRate: 60,
    notes: "Thiếu 2 công nhân",
  },
]

export const productionCapacities: ProductionCapacity[] = [
  {
    productionLineId: "line-1",
    productionLineName: "Dây chuyền viên nén số 1",
    type: "tablet",
    dailyCapacity: 150000,
    weeklyCapacity: 900000,
    monthlyCapacity: 3600000,
    unit: "viên",
    currentUtilization: 75,
  },
  {
    productionLineId: "line-2",
    productionLineName: "Dây chuyền viên nén số 2",
    type: "tablet",
    dailyCapacity: 135000,
    weeklyCapacity: 810000,
    monthlyCapacity: 3240000,
    unit: "viên",
    currentUtilization: 60,
  },
  {
    productionLineId: "line-3",
    productionLineName: "Dây chuyền viên nang số 1",
    type: "capsule",
    dailyCapacity: 120000,
    weeklyCapacity: 720000,
    monthlyCapacity: 2880000,
    unit: "viên",
    currentUtilization: 85,
  },
  {
    productionLineId: "line-4",
    productionLineName: "Dây chuyền xi-rô số 1",
    type: "syrup",
    dailyCapacity: 6000,
    weeklyCapacity: 36000,
    monthlyCapacity: 144000,
    unit: "chai",
    currentUtilization: 45,
  },
  {
    productionLineId: "line-5",
    productionLineName: "Dây chuyền viên nén số 3",
    type: "tablet",
    dailyCapacity: 120000,
    weeklyCapacity: 720000,
    monthlyCapacity: 2880000,
    unit: "viên",
    currentUtilization: 0,
  },
]

// BOM (Bill of Materials) Mock Data

export const bomFormulas: BOMFormula[] = [
  {
    id: "bom-1",
    code: "BOM-PAR-500-V2.0",
    medicineId: "med-1",
    medicineName: "Paracetamol 500mg",
    medicineCode: "MED-VN-001",
    version: "2.0",
    versionNumber: 2,
    status: "active",
    bomItems: [
      {
        id: "bom-item-1",
        materialId: "mat-1",
        materialCode: "NL-001",
        materialName: "Paracetamol",
        category: "raw_material",
        quantityPerUnit: 0.5,
        unit: "g",
        wastagePercent: 2,
        notes: "Nguyên liệu chính",
      },
      {
        id: "bom-item-2",
        materialId: "mat-3",
        materialCode: "TĐ-001",
        materialName: "Tinh bột ngô",
        category: "excipient",
        quantityPerUnit: 0.15,
        unit: "g",
        wastagePercent: 1,
      },
      {
        id: "bom-item-3",
        materialId: "mat-4",
        materialCode: "TĐ-002",
        materialName: "Lactose monohydrate",
        category: "excipient",
        quantityPerUnit: 0.1,
        unit: "g",
        wastagePercent: 1,
      },
      {
        id: "bom-item-4",
        materialId: "mat-6",
        materialCode: "BB-002",
        materialName: "Vỉ nhôm PVC/Alu",
        category: "packaging",
        quantityPerUnit: 0.01,
        unit: "cuộn",
        wastagePercent: 3,
        notes: "10 viên/vỉ",
      },
    ],
    batchSize: 10000,
    batchUnit: "viên",
    effectiveDate: "2025-10-01",
    createdBy: "user-10",
    createdAt: "2025-09-15T10:00:00Z",
    approvedBy: "user-8",
    approvedAt: "2025-09-20T14:00:00Z",
    changeReason: "Cải tiến công thức để tăng độ ổn định",
    notes: "Công thức đã được kiểm nghiệm và phê duyệt",
  },
  {
    id: "bom-1-old",
    code: "BOM-PAR-500-V1.0",
    medicineId: "med-1",
    medicineName: "Paracetamol 500mg",
    medicineCode: "MED-VN-001",
    version: "1.0",
    versionNumber: 1,
    status: "inactive",
    bomItems: [
      {
        id: "bom-item-old-1",
        materialId: "mat-1",
        materialCode: "NL-001",
        materialName: "Paracetamol",
        category: "raw_material",
        quantityPerUnit: 0.5,
        unit: "g",
        wastagePercent: 2,
      },
      {
        id: "bom-item-old-2",
        materialId: "mat-3",
        materialCode: "TĐ-001",
        materialName: "Tinh bột ngô",
        category: "excipient",
        quantityPerUnit: 0.2,
        unit: "g",
        wastagePercent: 1,
      },
      {
        id: "bom-item-old-3",
        materialId: "mat-6",
        materialCode: "BB-002",
        materialName: "Vỉ nhôm PVC/Alu",
        category: "packaging",
        quantityPerUnit: 0.01,
        unit: "cuộn",
        wastagePercent: 3,
      },
    ],
    batchSize: 10000,
    batchUnit: "viên",
    effectiveDate: "2024-01-01",
    expiryDate: "2025-09-30",
    createdBy: "user-10",
    createdAt: "2023-12-01T10:00:00Z",
    approvedBy: "user-8",
    approvedAt: "2023-12-15T14:00:00Z",
  },
  {
    id: "bom-2",
    code: "BOM-AMO-500-V1.0",
    medicineId: "med-2",
    medicineName: "Amoxicillin 500mg",
    medicineCode: "MED-VN-002",
    version: "1.0",
    versionNumber: 1,
    status: "active",
    bomItems: [
      {
        id: "bom-item-5",
        materialId: "mat-2",
        materialCode: "NL-002",
        materialName: "Amoxicillin Trihydrate",
        category: "raw_material",
        quantityPerUnit: 0.6,
        unit: "g",
        wastagePercent: 3,
        notes: "API chính - kháng sinh",
      },
      {
        id: "bom-item-6",
        materialId: "mat-4",
        materialCode: "TĐ-002",
        materialName: "Lactose monohydrate",
        category: "excipient",
        quantityPerUnit: 0.15,
        unit: "g",
        wastagePercent: 1,
      },
      {
        id: "bom-item-7",
        materialId: "mat-3",
        materialCode: "TĐ-001",
        materialName: "Tinh bột ngô",
        category: "excipient",
        quantityPerUnit: 0.1,
        unit: "g",
        wastagePercent: 1,
      },
      {
        id: "bom-item-8",
        materialId: "mat-6",
        materialCode: "BB-002",
        materialName: "Vỉ nhôm PVC/Alu",
        category: "packaging",
        quantityPerUnit: 0.01,
        unit: "cuộn",
        wastagePercent: 3,
        notes: "10 viên/vỉ",
      },
    ],
    batchSize: 10000,
    batchUnit: "viên",
    effectiveDate: "2024-06-01",
    createdBy: "user-10",
    createdAt: "2024-05-10T10:00:00Z",
    approvedBy: "user-8",
    approvedAt: "2024-05-20T14:00:00Z",
  },
  {
    id: "bom-3",
    code: "BOM-SIRO-100-V1.0",
    medicineId: "med-3",
    medicineName: "Siro ho trẻ em 100ml",
    medicineCode: "MED-VN-003",
    version: "1.0",
    versionNumber: 1,
    status: "active",
    bomItems: [
      {
        id: "bom-item-9",
        materialId: "mat-1",
        materialCode: "NL-001",
        materialName: "Paracetamol",
        category: "raw_material",
        quantityPerUnit: 1.2,
        unit: "g",
        wastagePercent: 2,
      },
      {
        id: "bom-item-10",
        materialId: "mat-5",
        materialCode: "BB-001",
        materialName: "Chai nhựa HDPE 100ml",
        category: "packaging",
        quantityPerUnit: 1,
        unit: "cái",
        wastagePercent: 2,
      },
    ],
    batchSize: 1000,
    batchUnit: "chai",
    effectiveDate: "2024-03-01",
    createdBy: "user-10",
    createdAt: "2024-02-10T10:00:00Z",
    approvedBy: "user-8",
    approvedAt: "2024-02-20T14:00:00Z",
  },
  {
    id: "bom-4",
    code: "BOM-VIT-C-1000-V1.0",
    medicineId: "med-4",
    medicineName: "Vitamin C 1000mg",
    medicineCode: "MED-VN-004",
    version: "1.0",
    versionNumber: 1,
    status: "active",
    bomItems: [
      {
        id: "bom-item-11",
        materialId: "mat-3",
        materialCode: "TĐ-001",
        materialName: "Tinh bột ngô",
        category: "excipient",
        quantityPerUnit: 0.3,
        unit: "g",
        wastagePercent: 1,
      },
      {
        id: "bom-item-12",
        materialId: "mat-4",
        materialCode: "TĐ-002",
        materialName: "Lactose monohydrate",
        category: "excipient",
        quantityPerUnit: 0.2,
        unit: "g",
        wastagePercent: 1,
      },
      {
        id: "bom-item-13",
        materialId: "mat-6",
        materialCode: "BB-002",
        materialName: "Vỉ nhôm PVC/Alu",
        category: "packaging",
        quantityPerUnit: 0.01,
        unit: "cuộn",
        wastagePercent: 3,
      },
    ],
    batchSize: 10000,
    batchUnit: "viên",
    effectiveDate: "2024-08-01",
    createdBy: "user-10",
    createdAt: "2024-07-15T10:00:00Z",
    approvedBy: "user-8",
    approvedAt: "2024-07-25T14:00:00Z",
  },
]

export const formulaVersions: FormulaVersion[] = [
  {
    id: "ver-1",
    formulaId: "bom-1",
    version: "2.0",
    versionNumber: 2,
    status: "active",
    changeDate: "2025-10-01",
    changedBy: "user-10",
    changeReason: "Cải tiến công thức để tăng độ ổn định và giảm hao hụt",
    changes: [
      {
        type: "modified",
        materialName: "Tinh bột ngô",
        oldValue: "0.2g",
        newValue: "0.15g",
        description: "Giảm tỷ lệ tá dược để tối ưu chi phí",
      },
      {
        type: "added",
        materialName: "Lactose monohydrate",
        newValue: "0.1g",
        description: "Thêm tá dược mới để tăng độ ổn định",
      },
    ],
  },
  {
    id: "ver-2",
    formulaId: "bom-1-old",
    version: "1.0",
    versionNumber: 1,
    status: "inactive",
    changeDate: "2024-01-01",
    changedBy: "user-10",
    changeReason: "Công thức ban đầu",
    changes: [],
  },
]

export const materialRequirements: MaterialRequirement[] = [
  {
    id: "req-1",
    productionPlanId: "pp-2",
    productionPlanCode: "PP-2026-0002",
    medicineId: "med-1",
    medicineName: "Paracetamol 500mg",
    formulaId: "bom-1",
    formulaVersion: "2.0",
    plannedQuantity: 100000,
    requirements: [
      {
        materialId: "mat-1",
        materialCode: "NL-001",
        materialName: "Paracetamol",
        category: "raw_material",
        requiredQuantity: 51,
        unit: "kg",
        currentStock: 250,
        shortage: -199,
        suggestedPurchaseQuantity: 0,
      },
      {
        materialId: "mat-3",
        materialCode: "TĐ-001",
        materialName: "Tinh bột ngô",
        category: "excipient",
        requiredQuantity: 15.15,
        unit: "kg",
        currentStock: 180,
        shortage: -164.85,
        suggestedPurchaseQuantity: 0,
      },
      {
        materialId: "mat-4",
        materialCode: "TĐ-002",
        materialName: "Lactose monohydrate",
        category: "excipient",
        requiredQuantity: 10.1,
        unit: "kg",
        currentStock: 420,
        shortage: -409.9,
        suggestedPurchaseQuantity: 0,
      },
      {
        materialId: "mat-6",
        materialCode: "BB-002",
        materialName: "Vỉ nhôm PVC/Alu",
        category: "packaging",
        requiredQuantity: 1.03,
        unit: "cuộn",
        currentStock: 75,
        shortage: -73.97,
        suggestedPurchaseQuantity: 0,
      },
    ],
    calculatedAt: "2026-01-24T10:00:00Z",
  },
  {
    id: "req-2",
    productionPlanId: "pp-1",
    productionPlanCode: "PP-2026-0001",
    medicineId: "med-2",
    medicineName: "Amoxicillin 500mg",
    formulaId: "bom-2",
    formulaVersion: "1.0",
    plannedQuantity: 80000,
    requirements: [
      {
        materialId: "mat-2",
        materialCode: "NL-002",
        materialName: "Amoxicillin Trihydrate",
        category: "raw_material",
        requiredQuantity: 49.44,
        unit: "kg",
        currentStock: 30,
        shortage: 19.44,
        suggestedPurchaseQuantity: 50,
      },
      {
        materialId: "mat-4",
        materialCode: "TĐ-002",
        materialName: "Lactose monohydrate",
        category: "excipient",
        requiredQuantity: 12.12,
        unit: "kg",
        currentStock: 420,
        shortage: -407.88,
        suggestedPurchaseQuantity: 0,
      },
      {
        materialId: "mat-3",
        materialCode: "TĐ-001",
        materialName: "Tinh bột ngô",
        category: "excipient",
        requiredQuantity: 8.08,
        unit: "kg",
        currentStock: 180,
        shortage: -171.92,
        suggestedPurchaseQuantity: 0,
      },
      {
        materialId: "mat-6",
        materialCode: "BB-002",
        materialName: "Vỉ nhôm PVC/Alu",
        category: "packaging",
        requiredQuantity: 0.824,
        unit: "cuộn",
        currentStock: 75,
        shortage: -74.176,
        suggestedPurchaseQuantity: 0,
      },
    ],
    calculatedAt: "2026-01-23T14:00:00Z",
  },
]

