import type { ProcessQualityCheck, FinalInspection } from "./quality-types";

// Process Quality Checks - In-process inspections
export const processQualityChecks: ProcessQualityCheck[] = [
  {
    id: "pqc-1",
    code: "PQC-2025-0012",
    productionPlanId: "pp-1",
    productionPlanCode: "PP-2025-0012",
    processStage: "Phối trộn",
    batchNumber: "LOT-2025-0012",
    checkDate: "2025-01-24T09:30:00Z",
    inspector: "Hoàng Văn Em",
    tests: [
      {
        id: "test-1",
        testName: "Độ đồng nhất hỗn hợp",
        testMethod: "TCVN 12345",
        specification: "RSD ≤ 5%",
        result: "3.2%",
        status: "passed",
        testedBy: "Hoàng Văn Em",
        testedAt: "2025-01-24T09:45:00Z",
      },
      {
        id: "test-2",
        testName: "Độ ẩm",
        testMethod: "USP <921>",
        specification: "≤ 5%",
        result: "3.8%",
        status: "passed",
        testedBy: "Hoàng Văn Em",
        testedAt: "2025-01-24T10:00:00Z",
      },
    ],
    status: "passed",
  },
  {
    id: "pqc-2",
    code: "PQC-2025-0013",
    productionPlanId: "pp-2",
    productionPlanCode: "PP-2025-0013",
    processStage: "Sấy khô",
    batchNumber: "LOT-2025-0013",
    checkDate: "2025-01-24T11:00:00Z",
    inspector: "Hoàng Văn Em",
    tests: [
      {
        id: "test-3",
        testName: "Độ ẩm sau sấy",
        testMethod: "USP <921>",
        specification: "2-4%",
        result: "3.1%",
        status: "passed",
        testedBy: "Hoàng Văn Em",
        testedAt: "2025-01-24T11:30:00Z",
      },
      {
        id: "test-4",
        testName: "Kích thước hạt",
        testMethod: "TCVN 54321",
        specification: "80-120 mesh",
        result: "95 mesh",
        status: "passed",
        testedBy: "Hoàng Văn Em",
        testedAt: "2025-01-24T11:45:00Z",
      },
    ],
    status: "passed",
  },
  {
    id: "pqc-3",
    code: "PQC-2025-0014",
    productionPlanId: "pp-3",
    productionPlanCode: "PP-2025-0014",
    processStage: "Phối trộn",
    batchNumber: "LOT-2025-0014",
    checkDate: "2025-01-24T13:00:00Z",
    inspector: "Hoàng Văn Em",
    tests: [
      {
        id: "test-5",
        testName: "Độ đồng nhất hỗn hợp",
        testMethod: "TCVN 12345",
        specification: "RSD ≤ 5%",
        result: "",
        status: "in_progress",
        testedBy: "Hoàng Văn Em",
        testedAt: "2025-01-24T13:30:00Z",
      },
    ],
    status: "in_progress",
  },
  {
    id: "pqc-4",
    code: "PQC-2025-0015",
    productionPlanId: "pp-4",
    productionPlanCode: "PP-2025-0015",
    processStage: "Đóng gói",
    batchNumber: "LOT-2025-0015",
    checkDate: "2025-01-23T14:00:00Z",
    inspector: "Hoàng Văn Em",
    tests: [
      {
        id: "test-6",
        testName: "Khối lượng trung bình",
        testMethod: "USP <905>",
        specification: "±5%",
        result: "2.3%",
        status: "passed",
        testedBy: "Hoàng Văn Em",
        testedAt: "2025-01-23T14:30:00Z",
      },
      {
        id: "test-7",
        testName: "Độ kín",
        testMethod: "TCVN 67890",
        specification: "Không rò rỉ",
        result: "Đạt",
        status: "passed",
        testedBy: "Hoàng Văn Em",
        testedAt: "2025-01-23T14:45:00Z",
      },
    ],
    status: "passed",
  },
  {
    id: "pqc-5",
    code: "PQC-2025-0016",
    productionPlanId: "pp-5",
    productionPlanCode: "PP-2025-0016",
    processStage: "Phối trộn",
    batchNumber: "LOT-2025-0016",
    checkDate: "2025-01-22T10:00:00Z",
    inspector: "Hoàng Văn Em",
    tests: [
      {
        id: "test-8",
        testName: "Độ đồng nhất hỗn hợp",
        testMethod: "TCVN 12345",
        specification: "RSD ≤ 5%",
        result: "6.8%",
        status: "failed",
        testedBy: "Hoàng Văn Em",
        testedAt: "2025-01-22T10:30:00Z",
      },
    ],
    status: "failed",
    notes: "Cần phối trộn lại do không đồng nhất",
  },
];

// Final Inspections - Product release testing
export const finalInspections: FinalInspection[] = [
  {
    id: "fi-1",
    code: "FI-2025-0008",
    productionBatchId: "batch-1",
    batchNumber: "LOT-2025-0008",
    medicineName: "Paracetamol 500mg",
    medicineCode: "MED-001",
    quantity: 50000,
    unit: "viên",
    inspectionDate: "2025-01-20T09:00:00Z",
    inspector: "Hoàng Văn Em",
    tests: [
      {
        id: "fi-test-1",
        testName: "Hàm lượng hoạt chất",
        testMethod: "USP <621>",
        specification: "95.0-105.0%",
        result: "99.2%",
        status: "passed",
        testedBy: "Hoàng Văn Em",
        testedAt: "2025-01-20T10:00:00Z",
      },
      {
        id: "fi-test-2",
        testName: "Độ hòa tan",
        testMethod: "USP <711>",
        specification: "≥80% trong 30 phút",
        result: "92% trong 30 phút",
        status: "passed",
        testedBy: "Hoàng Văn Em",
        testedAt: "2025-01-20T11:00:00Z",
      },
      {
        id: "fi-test-3",
        testName: "Vi sinh",
        testMethod: "USP <61>",
        specification: "≤1000 CFU/g",
        result: "450 CFU/g",
        status: "passed",
        testedBy: "Hoàng Văn Em",
        testedAt: "2025-01-20T14:00:00Z",
      },
    ],
    overallStatus: "passed",
    releaseApproved: true,
    approvedBy: "Nguyễn Văn An",
    approvedAt: "2025-01-20T15:00:00Z",
    documents: [
      {
        id: "doc-fi-1",
        type: "coa",
        name: "Certificate of Analysis - LOT-2025-0008.pdf",
        url: "#",
        uploadedBy: "Hoàng Văn Em",
        uploadedAt: "2025-01-20T15:30:00Z",
      },
      {
        id: "doc-fi-2",
        type: "test_report",
        name: "Batch Testing Report - LOT-2025-0008.pdf",
        url: "#",
        uploadedBy: "Hoàng Văn Em",
        uploadedAt: "2025-01-20T15:30:00Z",
      },
    ],
  },
  {
    id: "fi-2",
    code: "FI-2025-0009",
    productionBatchId: "batch-2",
    batchNumber: "LOT-2025-0009",
    medicineName: "Amoxicillin 500mg",
    medicineCode: "MED-002",
    quantity: 30000,
    unit: "viên",
    inspectionDate: "2025-01-21T09:00:00Z",
    inspector: "Hoàng Văn Em",
    tests: [
      {
        id: "fi-test-4",
        testName: "Hàm lượng hoạt chất",
        testMethod: "USP <621>",
        specification: "90.0-120.0%",
        result: "102.5%",
        status: "passed",
        testedBy: "Hoàng Văn Em",
        testedAt: "2025-01-21T10:00:00Z",
      },
      {
        id: "fi-test-5",
        testName: "Độ hòa tan",
        testMethod: "USP <711>",
        specification: "≥75% trong 45 phút",
        result: "88% trong 45 phút",
        status: "passed",
        testedBy: "Hoàng Văn Em",
        testedAt: "2025-01-21T11:30:00Z",
      },
      {
        id: "fi-test-6",
        testName: "Vi sinh",
        testMethod: "USP <61>",
        specification: "≤1000 CFU/g",
        result: "320 CFU/g",
        status: "passed",
        testedBy: "Hoàng Văn Em",
        testedAt: "2025-01-21T15:00:00Z",
      },
    ],
    overallStatus: "passed",
    releaseApproved: true,
    approvedBy: "Nguyễn Văn An",
    approvedAt: "2025-01-21T16:00:00Z",
    documents: [
      {
        id: "doc-fi-3",
        type: "coa",
        name: "Certificate of Analysis - LOT-2025-0009.pdf",
        url: "#",
        uploadedBy: "Hoàng Văn Em",
        uploadedAt: "2025-01-21T16:30:00Z",
      },
    ],
  },
  {
    id: "fi-3",
    code: "FI-2025-0010",
    productionBatchId: "batch-3",
    batchNumber: "LOT-2025-0010",
    medicineName: "Vitamin C 1000mg",
    medicineCode: "MED-003",
    quantity: 20000,
    unit: "viên",
    inspectionDate: "2025-01-23T09:00:00Z",
    inspector: "Hoàng Văn Em",
    tests: [
      {
        id: "fi-test-7",
        testName: "Hàm lượng hoạt chất",
        testMethod: "USP <621>",
        specification: "95.0-105.0%",
        result: "",
        status: "in_progress",
        testedBy: "Hoàng Văn Em",
        testedAt: "2025-01-23T10:00:00Z",
      },
      {
        id: "fi-test-8",
        testName: "Độ hòa tan",
        testMethod: "USP <711>",
        specification: "≥80% trong 30 phút",
        result: "",
        status: "pending",
        testedBy: "",
        testedAt: "",
      },
    ],
    overallStatus: "in_progress",
    releaseApproved: false,
    documents: [],
  },
  {
    id: "fi-4",
    code: "FI-2025-0011",
    productionBatchId: "batch-4",
    batchNumber: "LOT-2025-0011",
    medicineName: "Ibuprofen 400mg",
    medicineCode: "MED-004",
    quantity: 40000,
    unit: "viên",
    inspectionDate: "2025-01-24T09:00:00Z",
    inspector: "Hoàng Văn Em",
    tests: [
      {
        id: "fi-test-9",
        testName: "Hàm lượng hoạt chất",
        testMethod: "USP <621>",
        specification: "95.0-105.0%",
        result: "",
        status: "pending",
        testedBy: "",
        testedAt: "",
      },
    ],
    overallStatus: "pending",
    releaseApproved: false,
    documents: [],
  },
];
